export default [
  { label: 'a', value: 8.16 },
  { label: 'b', value: 1.49 },
  { label: 'c', value: 2.78 },
  { label: 'd', value: 4.25 },
  { label: 'e', value: 12.70 },
  { label: 'f', value: 2.22 },
  { label: 'g', value: 2.01 },
  { label: 'h', value: 6.09 },
  { label: 'i', value: 6.96 },
  { label: 'j', value: 0.15 },
  { label: 'k', value: 0.77 },
  { label: 'l', value: 4.02 },
  { label: 'm', value: 2.40 },
  { label: 'n', value: 6.74 },
  { label: 'o', value: 7.50 },
  { label: 'p', value: 1.92 },
  { label: 'q', value: 0.09 },
  { label: 'r', value: 5.98 },
  { label: 's', value: 6.32 },
  { label: 't', value: 9.05 },
  { label: 'u', value: 2.75 },
  { label: 'v', value: 0.97 },
  { label: 'w', value: 2.36 },
  { label: 'x', value: 0.15 },
  { label: 'y', value: 1.97 },
  { label: 'z', value: 0.07 }
]
